### ISSUE TITLE
Can not find Module 'lottie-vuejs'

### ISSUE THREAD

**Issue by qqaimh** [SuperbuffNL/lottie-vuejs#1]
When I use typescript in "vue": "^2.6.10" , then : Can not find Module 'lottie-vuejs'

**Comment by IndianTinker** [comment]
Same issue when using with nuxtjs.

**Comment by Ralph89** [comment]
Currently only working with Javascript

**Comment by austinstudio** [comment]
Has this been resolved?  Does this mean we can't use Lottie if we are using TypeScript?
