### ISSUE TITLE
Dependency was not found error when using 0.3.7

### ISSUE THREAD

**Issue by aullman** [SuperbuffNL/lottie-vuejs#3]
dist folder is missing in version 0.3.7 I guess you forgot to do an npm run build before an npm publish?

**Comment by ltakato** [comment]
@aullman sure. I needed to downgrade to 0.3.6

**Comment by ltakato** [comment]
+1 👍

**Comment by imsidz** [comment]
i am also getting dependency not found

**Comment by namexbalboa** [comment]
+1

**Comment by ali26Y** [comment]
+ 1

**Comment by laszloszucs** [comment]
It's working for me: [vue-lottie](https://www.npmjs.com/package/vue-lottie)

lottie-vuejs has more issue than Dependency was found.
I'm tried the 0.3.6 and the "lottie-animation" component was not found...

**Comment by kvn29** [comment]
+1

**Comment by canvasandcode** [comment]
+1

**Comment by MaritzaVst** [comment]
+1

**Comment by michaelfitzhavey** [comment]
+1 for me @aullman. I'd be happy to help out with this if you have any contribution guidelines 😃

**Comment by MLDMoritz** [comment]
0.3.7 is broken, why is the package still live? @superbuffdev

**Comment by michaelfitzhavey** [comment]
@MLDMoritz / anyone else if you are looking for a similar package, since commenting in this threat I've created: https://www.npmjs.com/package/lottie-player-vue. It works as documented and contributions are very welcome.

**Comment by Ralph89** [comment]
I will have a look tomorrow

**Comment by pehlse** [comment]
+1

**Comment by alexanderkon** [comment]
We made it work like this 
`import LottieAnimation from "lottie-vuejs/src/LottieAnimation.vue";`

**Comment by shandhiviyarajan** [comment]
stupid plugin 
loads to the animation source with absolute path and adding the "/ " or api url to it.

**Comment by Ralph89** [comment]
Hi all,

Sorry for the inconvenience, I have made a new version. Problem should be resolved

Make sure use: import LottieAnimation from "lottie-vuejs/src/LottieAnimation.vue";
